name = "gabbaichabad"
compatibility_date = "2026-04-02"
main = "./worker.js"

[assets]
directory = "."
binding = "ASSETS"
run_worker_first = ["/api/*"]

[[kv_namespaces]]
binding = "GABBAI_KV"
id = "a2f9477506b9488ca364e958519c8ead"

[observability.logs]
enabled = false
invocation_logs = true
